# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    swift_message:
        class: Swift_Message

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Listener\:
        resource: '../../src/AppBundle/Listener'
        public: true
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    AppBundle\Service\:
        resource: '../../src/AppBundle/Service'
        public: true
        tags: ['mailer', 'swift_message', "@doctrine.orm.entity_manager", '@service_container']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
